### PR TITLE
added exponentiate function and driver code

### PR DESCRIPTION
**Pull request by Patoucheas**
also added try catch expection to log func

### CODE REVIEW

**Review by mpatel136 — APPROVED** [review]
Use of Math class, will approve for now. Needs to be changed with helper function.

**Review by ifelsemaybe — COMMENTED** [review]
looks good, merge it

**Review by ifelsemaybe — COMMENTED** [review]
its good

**Review by ifelsemaybe — APPROVED** [review]

**Review by mpatel136 — APPROVED** [review]
Use of Math class, will approve for now. Needs to be changed with helper function.

**Pull request merged**
